#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'getTotalX' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def getTotalX(a, b):
   
    lower_limit = max(a)  
    upper_limit = min(b) 
    
    count = 0  
    

    for x in range(lower_limit, upper_limit + 1):

        is_multiple_of_a = all(x % num == 0 for num in a)
        is_divisor_of_b = all(num % x == 0 for num in b)
        
        if is_multiple_of_a and is_divisor_of_b:
            count += 1
    
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    brr = list(map(int, input().rstrip().split()))

    total = getTotalX(arr, brr)

    fptr.write(str(total) + '\n')

    fptr.close()
