#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'breakingRecords' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY scores as parameter.
#

def breakingRecords(scores):
    
    highest = scores[0]
    lowest = scores[0]
    
    indexP = 0
    indexN = 0
    
    for i in range (1, len(scores)):
        if scores[i] > highest:
            highest = scores[i]
            indexP = indexP + 1
        elif scores[i] < lowest:
            lowest = scores[i]
            indexN = indexN + 1
        
    return [indexP,indexN]    
             
         

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
